lmia:
    target: dev
    outputs:
        dev:
            type: bigquery
            method: service-account
            keyfile: /root/.dbt/service_account_key.json
            project: durable-bond-447600-a5
            dataset: lmia
            threads: 1
            timeout_seconds: 300
            location: US
            priority: interactive