version: 2

models:
  - name: stg_lmia
    description: table containing the quarterly applications to the labour market intake assessments used by the government of canada before they can hire temporary foreign workers
    columns:
      - name: period
        description: The quarter of the report
        tests:
          - accepted_values:
              values: ['2024-Q1','2024-Q2','2024-Q3']
      - name: stream
        description: The category of wage stream that the application was made for
        tests:
          - accepted_values:
              values: ['Global Talent Stream', 'High Wage', 'Low Wage', 'Primary Agriculture', 'Permanent Resident Only']
      - name: employer
        description: The name of the employer
      - name: city
        description: The city that the employer resides in
      - name: postal_code
        description: The employer's postal code
      - name: province
        description: the province that the employer is located in
        tests:
          - accepted_values:
              values: ['Newfoundland and Labrador',
                      'Prince Edward Island',
                      'Nova Scotia',
                      'New Brunswick',
                      'Quebec',
                      'Ontario',
                      'Manitoba',
                      'Saskatchewan',
                      'Alberta',
                      'British Columbia',
                      'Northwest Territories',
                      'Yukon',
                      'Nunavut',
                      'Employers carrying on business in Canada with Head Office outside of Canada']
      - name: occupation_code
        description: The occupation/noc code of the applied for LMIA
      - name: occupation_name
        description: The name of the occupation for which the LMIA
      - name: approved_lmias
        description: The number of LMIA applications that were submitted and approved
        tests:
          - not_null
      - name: approved_positions
        description: The number of positions that were created as a result of the LMIA's submitted
        tests:
          - not_null
  - name: mart_approved_by_employer
    description: view of how many total lmia applications and jobs were accepted
    columns:
      - name: employer
        description: The name of the employer
        tests:
          - unique
      - name: approved_lmias
        description: The sum of all lmias approved by the employer
      - name: approved_positions
        description: The sum of all positions that were approved
  - name: mart_approved_by_prov
    description: view of how many applications were submitted and jobs available by province
    columns:
      - name: province
        description: the name of the province
        tests:
          - unique
      - name: approved_lmias
        description: The sum of all lmias approved by the employer
      - name: approved_positions
        description: The sum of all positions that were approved
  - name: mart_approved_by_quarter
    description: view of how many applications are approved by quarter
    columns:
      - name: period
        description: The quarter
        tests:
          - unique
      - name: approved_lmias
        description: The sum of all lmias approved by the employer
      - name: approved_positions
        description: The sum of all positions that were approved  